### ISSUE TITLE
Variable not initialized

### ISSUE THREAD

**Issue by jtrod** [TappNetwork/laravel-uppy-s3-multipart-upload#1]
Hi great package, very helpful..  Thanks a lot.

I was wondering where the **$partResponse['NextPartNumberMarker']** is being initialized at line 172. My IDE flags it as not initialized, even though this being a recursive call.

https://github.com/TappNetwork/laravel-uppy-s3-multipart-upload/blob/4d00b9edba34e83a011482ea3691637270df971f/src/Http/Controllers/UppyS3MultipartController.php#L157-L175

**Comment by andreia** [comment]
@jtrod Thank you, really glad you found it helpful! 
I just added a fix.
Please let me know if everything is okay :)

**Comment by jtrod** [comment]
Awesome! Thanks for sharing this with the community! 
Very helpful!
