### ISSUE TITLE
Incompatable with latest version of Uppy

### ISSUE THREAD

**Issue by kaptk2** [TappNetwork/laravel-uppy-s3-multipart-upload#17]
When Uppy version 3 is installed like this:
```
"@uppy/aws-s3-multipart": "^3.1.2",
"@uppy/core": "^3.0.5",
"@uppy/drag-drop": "^3.0.1",
"@uppy/status-bar": "^3.0.1",
```
a 404 error is thrown as soon as a file is uploaded.

Using version 2.0.2 as recommend in the documentation works.

**Comment by oyarzun** [comment]
SignPart needs to be implemented in the [controller](https://github.com/TappNetwork/laravel-uppy-s3-multipart-upload/blob/master/src/Http/Controllers/UppyS3MultipartController.php). 
https://uppy.io/docs/aws-s3-multipart/#signPart-file-partData

**Comment by andreia** [comment]
@kaptk2 @oyarzun Thanks for the heads up! :)
I just added a new release (https://github.com/TappNetwork/laravel-uppy-s3-multipart-upload/releases/tag/v1.0) with this update.
Please let me know if everything is working for you.

**Comment by kaptk2** [comment]
Everything is working great for me. We've had it in production for a couple weeks without a hiccup. Closing this issue now

**Comment by andreia** [comment]
@kaptk2 Awesome! Thank you for the feedback :)

**Comment by Fsilien** [comment]
Hello. Thank you again for this beautiful package. I have a problem. I
followed all the steps of the last version to add it to my project and it
shows me no errors. to my astonishment when I tried to use the in my form
it only shows me this text: Uploaded file: nothing yet. Can you help me
please.
