### ISSUE TITLE
It doesn't work with uppy v2

### ISSUE THREAD

**Issue by jtrod** [TappNetwork/laravel-uppy-s3-multipart-upload#5]
Uppy Companion V2, now handles, signature batching. Unfortunately I don't have time to contribute but I wish...
This will solve your issue in your controller and make it Uppy 2 compatible:

    public function prepareUploadPart(Request $request, $uploadId, $batch)
    {
        $key = $this->encodeURIComponent($request->input('key'));

        $partNumbers = explode(",", $request->partNumbers);

        $urls = [];
        foreach ($partNumbers as $partNumber) {
            $command = $this->client->getCommand('uploadPart', [
                'Bucket'     => $this->bucket,
                'Key'        => $key,
                'UploadId'   => $uploadId,
                'PartNumber' =>  (int) $partNumber,
                'Body'       => '',
            ]);

            $urls[$partNumber] = (string) $this->client->createPresignedRequest($command, '+2 hour')->getUri();
        }

        return response()
            ->json([
                'presignedUrls' => $urls,
            ]);
    }

**Comment by unitidev** [comment]
> Uppy Companion V2, now handles, signature batching. Unfortunately I don't have time to contribute but I wish...
> This will solve your issue in your controller and make it Uppy 2 compatible:
> 
> ```
> public function prepareUploadPart(Request $request, $uploadId, $batch)
> {
>     $key = $this->encodeURIComponent($request->input('key'));
> 
>     $partNumbers = explode(",", $request->partNumbers);
> 
>     $urls = [];
>     foreach ($partNumbers as $partNumber) {
>         $command = $this->client->getCommand('uploadPart', [
>             'Bucket'     => $this->bucket,
>             'Key'        => $key,
>             'UploadId'   => $uploadId,
>             'PartNumber' =>  (int) $partNumber,
>             'Body'       => '',
>         ]);
> 
>         $urls[$partNumber] = (string) $this->client->createPresignedRequest($command, '+2 hour')->getUri();
>     }
> 
>     return response()
>         ->json([
>             'presignedUrls' => $urls,
>         ]);
> }
> ```

You saved my life, Thank you. !!!

**Comment by andreia** [comment]
Thank you @jtrod !
Created a PR for it: https://github.com/TappNetwork/laravel-uppy-s3-multipart-upload/pull/6

**Comment by jtrod** [comment]
No, thanks to you for this nice package! 👍
