### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by gilbitron** [TappNetwork/laravel-uppy-s3-multipart-upload#9]
Trying to install this on a Laravel 9 project but get the following composer error:

```
  Problem 1
    - Root composer.json requires tapp/laravel-uppy-s3-multipart-upload ^0.4.0 -> satisfiable by tapp/laravel-uppy-s3-multipart-upload[v0.4.0].
    - tapp/laravel-uppy-s3-multipart-upload v0.4.0 requires illuminate/contracts ^8.0 -> found illuminate/contracts[v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
```

Any chance we can get `illuminate/contracts` upgraded to v9?

**Comment by swilla** [comment]
@gilbitron just tagged a new release with Laravel 9 support:
https://github.com/TappNetwork/laravel-uppy-s3-multipart-upload/releases/tag/v0.5.0

**Comment by gilbitron** [comment]
Just a heads up, I know your tests are passing but [Laravel 9 requires Flysystem v3](https://laravel.com/docs/9.x/upgrade#flysystem-3) which has a new API. For example, the following line will be broken as the `getAdapter` method no longer exists:

```php
Storage::disk('s3')->getDriver()->getAdapter()->getClient();
```

**Comment by andreia** [comment]
@gilbitron Added a new release to fix it https://github.com/TappNetwork/laravel-uppy-s3-multipart-upload/releases/tag/v0.5.1
